fix: prevent collectd version-gen.sh from picking up parent git repo
collectd configure runs git describe which traverses up to /workdir/openwrt/.git,
setting LCC_VERSION_PATCH to '0-r54' (a bare identifier) causing compile failure:
  error: 'r54' undeclared

Fixed by setting GIT_CEILING_DIRECTORIES to stop git traversal at collectd build dir.